### ISSUE TITLE
Install failed on macOS x86

### ISSUE THREAD

**Issue by ksurya** [allenai/tango#342]
### 🐛 Describe the bug

```
pip install -U ai2-tango
Collecting ai2-tango
  Using cached ai2_tango-0.10.0-py3-none-any.whl (197 kB)
Collecting filelock<3.8,>=3.4
  Using cached filelock-3.7.1-py3-none-any.whl (10 kB)
Collecting tqdm<4.65,>=4.62
  Downloading tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 3.3 MB/s eta 0:00:00
Collecting cached-path<1.2,>=1.0
  Using cached cached_path-1.1.5-py3-none-any.whl (26 kB)
Requirement already satisfied: pytz in ./anaconda3/lib/python3.7/site-packages (from ai2-tango) (2019.3)
Collecting petname<3.0,>=2.6
  Using cached petname-2.6.tar.gz (8.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/gl/bb_x4r9s71x3rdmkm7x849200000gn/T/pip-install-ap4rel_a/petname_ca9da410f6c447f48ef483a228de6923/setup.py", line 40, in <module>
          'petname = petname.__main__:main',
        File "/Users/me1/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/Users/me1/anaconda3/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 139, in setup
          _setup_distribution = dist = klass(attrs)
        File "/Users/me1/anaconda3/lib/python3.7/site-packages/setuptools/dist.py", line 481, in __init__
          for k, v in attrs.items()
        File "/Users/me1/anaconda3/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 275, in __init__
          self.finalize_options()
        File "/Users/me1/anaconda3/lib/python3.7/site-packages/setuptools/dist.py", line 900, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "/Users/me1/anaconda3/lib/python3.7/site-packages/setuptools/dist.py", line 899, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "/Users/me1/anaconda3/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 196, in load
          return functools.reduce(getattr, attrs, module)
      AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### Versions

pip 22.2 from /Users/suryak/anaconda3/lib/python3.7/site-packages/pip (python 3.7)
absl-py==0.10.0
aiofiles==0.5.0
alabaster==0.7.12
alembic==1.0.1
allennlp==0.8.4
altair==4.2.0
anaconda-client==1.7.2
anaconda-navigator==1.9.7
anaconda-project==0.8.3
aniso8601==7.0.0
ansi2html==1.7.0
apache-beam==2.16.0
appnope==0.1.0
appscript==1.1.0
arrow==1.2.2
asn1crypto==0.24.0
astroid==2.3.3
astropy==4.0.1.post1
astunparse==1.6.3
async-exit-stack==1.0.1
async-generator==1.10
atomicwrites==1.3.0
attrs==18.1.0
Automat==0.7.0
autopep8==1.4.4
av==8.0.2
avro-python3==1.9.1
awscli==1.16.210
Babel==2.8.0
backcall==0.1.0
backports.functools-lru-cache==1.6.1
backports.os==0.1.1
backports.shutil-get-terminal-size==1.0.0
backports.tempfile==1.0
backports.weakref==1.0.post1
backports.zoneinfo==0.2.1
beautifulsoup4==4.9.0
binaryornot==0.4.4
bitarray==1.2.1
bkcharts==0.2
bleach==3.1.4
blinker==1.4
blis==0.2.4
bokeh==2.0.1
boto==2.49.0
boto3==1.9.200
botocore==1.12.200
Bottleneck==1.3.2
briefcase==0.3.8
Brotli==1.0.9
browser-cookie3==0.11.1
CacheControl==0.12.6
cachetools==4.1.1
certifi==2020.6.20
cffi==1.11.5
chardet==3.0.4
click==8.0.1
cloudpickle==1.3.0
clyent==1.2.2
colorama==0.4.3
commonmark==0.9.1
conda==4.9.0
conda-build==3.18.8
conda-package-handling==1.6.0
conda-verify==3.4.2
ConfigArgParse==1.2.3
configparser==4.0.2
conllu==0.11
constantly==15.1.0
contextlib2==0.6.0.post1
cookiecutter==2.1.1
coursera-dl==0.11.5
crcmod==1.7
cryptography==2.3
cssselect==1.0.3
cycler==0.10.0
cymem==2.0.2
Cython==0.29.16
cytoolz==0.10.1
dash==2.5.1
dash-core-components==2.0.0
dash-html-components==2.0.0
dash-table==5.0.0
dask==2.14.0
databricks-cli==0.9.1
decorator==4.4.2
defusedxml==0.6.0
dill==0.3.0
distributed==2.14.0
dmgbuild==1.5.2
dnspython==2.0.0
docker==4.1.0
docopt==0.6.2
docutils==0.16
ds-store==1.3.0
editdistance==0.5.3
email-validator==1.1.1
en-core-web-sm==2.1.0
entrypoints==0.3
enum34==1.1.6
ERAlchemy==1.2.10
et-xmlfile==1.0.1
fake-useragent==0.1.11
fastapi==0.61.1
fastavro==0.21.24
fastcache==1.1.0
feedparser==6.0.1
filelock==3.0.10
firebase-admin==4.4.0
flaky==3.6.0
Flask==2.0.1
Flask-Compress==1.12
Flask-Cors==3.0.9
fsspec==0.7.2
ftfy==5.5.1
future==0.18.2
gast==0.3.3
gdata==2.0.18
gevent==1.4.0
gitdb==4.0.9
gitdb2==2.0.6
GitPython==3.1.27
glob2==0.7
gmpy2==2.1.0b1
google-api-core==1.22.4
google-api-python-client==1.12.4
google-auth==1.21.2
google-auth-httplib2==0.0.4
google-auth-oauthlib==0.4.1
google-cloud-core==1.4.3
google-cloud-datastore==2.1.3
google-cloud-firestore==2.1.3
google-cloud-storage==1.32.0
google-crc32c==1.0.0
google-pasta==0.2.0
google-resumable-media==1.1.0
googleapis-common-protos==1.52.0
gorilla==0.3.0
graphene==2.1.8
graphql-core==2.3.2
graphql-relay==2.0.1
greenlet==0.4.15
grpcio==1.32.0
gunicorn==20.0.0
h11==0.9.0
h5py @ file:///Users/runner/miniforge3/conda-bld/h5py_1595110209982/work
hdfs==2.5.8
HeapDict==1.0.1
html2text==2020.1.16
html5lib==1.0.1
httplib2==0.18.1
httptools==0.1.1
huggingface-hub==0.8.1
hyperjson==0.2.4
hyperlink==18.0.0
hypothesis==5.8.0
idna==2.7
imageio==2.8.0
imageio-ffmpeg==0.4.2
imagesize==1.2.0
importlib-metadata==1.6.0
incremental==17.5.0
ipaddress==1.0.22
ipdb==0.12.2
ipykernel==5.2.0
ipython==7.13.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
isodate==0.6.0
isort==4.3.21
itsdangerous==2.0.1
jdcal==1.4.1
jedi==0.15.2
Jinja2==3.0.1
jinja2-time==0.2.0
jmespath==0.9.4
joblib==0.14.1
json5==0.9.0
jsonnet==0.13.0
jsonpickle==1.2
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.2
jupyter-console==6.1.0
jupyter-core==4.6.3
jupyter-dash==0.4.2
jupyterlab==1.2.6
jupyterlab-server==1.1.0
jupyterthemes==0.20.0
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
keyring==21.1.1
kiwisolver==1.2.0
lazy-object-proxy==1.4.3
lesscpy==0.13.0
libarchive-c==2.9
libcst==0.3.19
lief==0.9.0
llvmlite==0.31.0
locket==0.2.0
lxml==4.2.4
lz4==3.0.2
mac-alias==2.2.0
Mako==1.0.7
Markdown==3.2.2
MarkupSafe==2.0.1
matplotlib==3.2.1
mccabe==0.6.1
mistune==0.8.4
mkl-fft==1.1.0
mkl-random==1.1.0
mkl-service==2.3.0
mlflow==1.4.0
mock==3.0.5
more-itertools==8.2.0
mpmath==1.1.0
msgpack==1.0.0
multipledispatch==0.6.0
murmurhash==1.0.2
mypy-extensions==0.4.3
navigator-updater==0.2.1
nbconvert==5.6.1
nbdime==1.1.0
nbformat==5.0.4
neo4j==1.7.6
neobolt==1.7.15
neotime==1.7.4
nest-asyncio==1.5.5
networkx==2.4
nltk==3.4.4
nodejs==0.1.1
nose==1.3.7
notebook==6.0.3
numba==0.48.0
numexpr==2.7.1
numpy==1.18.1
numpydoc==0.9.2
oauth2client==3.0.0
oauthlib==3.1.0
olefile==0.46
onnx==1.8.0
onnxruntime==1.3.0
openpyxl==3.0.3
opt-einsum==3.3.0
optional-django==0.1.0
orjson==3.4.0
overrides==1.9
packaging==20.1
pandas==1.0.3
pandocfilters==1.4.2
parsel==1.5.0
parsimonious==0.8.1
parso==0.6.2
partd==1.1.0
path==13.1.0
pathlib2==2.3.5
patsy==0.5.1
pbkdf2==1.3
pbr==5.4.3
pep8==1.7.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.2.0
pkginfo==1.5.0.1
plac==0.9.6
plaidbench==0.6.4
plaidml==0.6.4
plaidml-keras==0.6.4
plotly==5.9.0
pluggy==0.12.0
ply==3.11
praw==6.4.0
prawcore==1.0.1
preshed==2.0.1
prometheus-client==0.7.1
promise==2.3
prompt-toolkit==3.0.5
proto-plus==1.19.0
protobuf==3.13.0
protobuf3==0.2.1
psutil==5.9.1
ptvsd==4.3.2
ptyprocess==0.6.0
py==1.8.1
pyaes==1.6.1
pyarrow==0.14.1
pyasn1==0.4.6
pyasn1-modules==0.2.2
pycodestyle==2.4.0
pycosat==0.6.3
pycparser==2.18
pycrypto==2.6.1
pycryptodome==3.9.7
pycurl==7.43.0.5
pydantic==1.6.1
pydeck==0.7.1
PyDispatcher==2.0.5
pydot==1.4.1
pyflakes==2.2.0
Pygments==2.6.1
pygraphviz==1.3
PyHamcrest==1.9.0
pylint==2.4.4
pymongo==3.9.0
Pympler==1.0.1
pyodbc==4.0.30
pyOpenSSL==18.0.0
pyparsing==2.4.7
pyrsistent==0.16.0
pysimdjson==3.2.0
pysm==0.3.9
PySocks==1.7.1
pytest==5.4.1
pytest-arraydiff==0.3
pytest-astropy==0.7.0
pytest-astropy-header==0.1.2
pytest-doctestplus==0.4.0
pytest-openfiles==0.4.0
pytest-remotedata==0.3.1
python-dateutil==2.7.3
python-dotenv==0.9.1
python-editor==1.0.3
python-gflags==3.1.2
python-Levenshtein==0.12.0
python-multipart==0.0.5
python-rapidjson==1.0
python-slugify==6.1.2
pytorch-pretrained-bert==0.6.2
-e git+ssh://git@github.com/huggingface/pytorch-transformers@40acf6b52a5250608c2b90edd955835131971d5a#egg=pytorch_transformers
pytz==2019.3
pytz-deprecation-shim==0.1.0.post0
PyWavelets==1.1.1
PyYAML==5.3.1
pyzmq==19.0.0
QtAwesome==0.7.0
qtconsole==4.7.2
QtPy==1.9.0
querystring-parser==1.2.4
queuelib==1.5.0
rdflib==4.2.2
redis==3.5.3
regex==2019.6.8
requests==2.24.0
requests-oauthlib==1.3.0
responses==0.10.6
retrying==1.3.3
rich==12.4.4
rope==0.16.0
rsa==4.0
ruamel-yaml==0.15.80
rubicon-objc==0.4.2
Rx==1.6.1
s3transfer==0.2.1
sacremoses==0.0.35
scikit-image==0.17.2
scikit-learn==0.22.2.post1
scipy==1.4.1
Scrapy==1.5.1
scrapy-crawlera==1.5.0
scrapy-fake-useragent==1.1.0
scrapyd==1.2.0
scrapyd-client==1.2.0a1
seaborn==0.10.0
selenium==3.141.0
semver==2.13.0
Send2Trash==1.5.0
sentencepiece==0.1.83
service-identity==17.0.0
service-streamer==0.1.2
sgmllib3k==1.0.0
simplegeneric==0.8.1
simplejson==3.16.0
singledispatch==3.4.0.3
sip==4.19.20
six==1.15.0
smmap==5.0.0
smmap2==2.0.5
snowballstemmer==2.0.0
sortedcollections==1.1.2
sortedcontainers==2.1.0
soupsieve==1.9.4
spacy==2.1.7
Sphinx==3.0.1
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
sphinxcontrib-websupport==1.2.1
spyder==3.3.6
spyder-kernels==0.5.1
SQLAlchemy==1.2.10
sqlparse==0.3.0
srsly==0.0.7
starlette==0.13.6
statsmodels==0.11.1
std-nslog==1.0.1
streamlit==1.10.0
sympy==1.5.1
tables==3.6.1
tabulate==0.8.5
tblib==1.6.0
tenacity==8.0.1
tensorboard==2.3.0
tensorboard-plugin-wit==1.7.0
tensorboardX==1.8
tensorflow==2.3.0
tensorflow-estimator==2.3.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
text-unidecode==1.3
textblob==0.15.3
thinc==7.0.8
tifffile==2020.9.3
toga==0.3.0.dev34
toga-chart==0.1.0
toga-cocoa==0.3.0.dev34
toga-core==0.3.0.dev34
tokenizers==0.12.1
toml==0.10.2
tomli==2.0.1
toolz==0.10.0
torch==1.6.0
torchserve==0.2.0
torchvision==0.7.0
tornado==6.0.4
tqdm==4.45.0
traitlets==4.3.3
transformers==4.20.1
transitions==0.8.5
travertino==0.1.3
Twisted==18.7.0
typed-ast==1.4.1
typing-inspect==0.7.1
typing_extensions==4.3.0
tzdata==2022.1
tzlocal==4.2
ujson==3.2.0
unicodecsv==0.14.1
Unidecode==1.1.1
update-checker==0.16
uritemplate==3.0.1
urllib3==1.24.3
uvicorn==0.11.8
uvloop==0.14.0
validators==0.20.0
virtualenv==16.7.8
w3lib==1.19.0
wasabi==0.2.2
watchdog==2.1.9
wcwidth==0.1.9
webencodings==0.5.1
websocket-client==0.56.0
websockets==8.0.2
Werkzeug==2.0.1
widgetsnbextension==3.5.1
word2number==1.1
wordcloud==1.8.2.2
wrapt==1.12.1
wurlitzer==2.0.0
xlrd==1.2.0
XlsxWriter==1.2.8
xlwings==0.18.0
xlwt==1.3.0
zict==2.0.0
zipp==3.1.0
zope.interface==5.1.0

**Comment by epwalsh** [comment]
Hmm, looks like the issue is with the `petname` package. Can you try installing `petname` with conda?

`conda install -c conda-forge petname`
