### ISSUE TITLE
Cannot recover value when using the Beaker Executor

### ISSUE THREAD

**Issue by schmmd** [allenai/tango#357]
### 🐛 Describe the bug

I created a simple example that has a single step that returns `5`.  When I run it without a `tango.yml` the following code recovers the number `5`:

```
>>> from tango import Workspace
>>> workspace = Workspace.from_url("local:///Users/michaels/hack/allenai/tango-test/workspace")
>>> workspace.step_result_for_run("fancy-dingo", "main") 
5
```

However, when I use the following tango.yml I get an exception instead.

```
executor:
  type: beaker
  beaker_workspace: ai2/michaels-default
  clusters:
    - ai2/general-cirrascale
  docker_image: ghcr.io/allenai/pytorch:1.12.0-cuda11.3-python3.9
  venv_name: base
```

```
>>> from tango import Workspace
>>> workspace = Workspace.from_url("local:///Users/michaels/hack/allenai/tango-test/workspace")
>>> workspace.step_result_for_run("calm-squid", "main") 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/michaels/hack/allenai/tango/tango/workspace.py", line 240, in step_result_for_run
    return self.step_cache[step_info]
  File "/Users/michaels/hack/allenai/tango/tango/step_caches/local_step_cache.py", line 115, in __getitem__
    raise KeyError(step)
KeyError: StepInfo(unique_id='Main-4jtQuipCnThKTpamAPe4JAhrViYmmWHK', step_class_name='Main', dependencies=set(), cacheable=True, step_name='main', version=None, start_time=None, end_time=None, error=None, result_location=None, config={'type': 'main'}, platform=PlatformMetadata(operating_system='macOS-10.16-x86_64-i386-64bit', cpu_count=16, user='michaels', host='ip-172-16-21-35.us-west-2.compute.internal'), environment=EnvironmentMetadata(python='3.9.12', executable=PosixPath('/Users/michaels/miniconda3/envs/tango/bin/python'), command='/Users/michaels/miniconda3/envs/tango/bin/tango run steps.jsonnet -i main -w workspace', root=PosixPath('/Users/michaels/hack/allenai/tango-test'), packages=[('absl-py', '1.2.0'), ('ai2-tango', '0.11.0'), ('aiohttp', '3.8.1'), ('aiosignal', '1.2.0'), ('astunparse', '1.6.3'), ('async-timeout', '4.0.2'), ('attrs', '22.1.0'), ('base58', '2.1.1'), ('beaker-py', '1.6.9'), ('boto3', '1.24.48'), ('botocore', '1.27.48'), ('cached-path', '1.1.5'), ('cachetools', '5.2.0'), ('certifi', '2022.6.15'), ('charset-normalizer', '2.1.0'), ('chex', '0.1.4'), ('click', '8.1.3'), ('click-help-colors', '0.9.1'), ('commonmark', '0.9.1'), ('cycler', '0.11.0'), ('datasets', '2.4.0'), ('dill', '0.3.5.1'), ('dm-tree', '0.1.7'), ('docker', '5.0.3'), ('docker-pycreds', '0.4.0'), ('etils', '0.7.1'), ('fairscale', '0.4.6'), ('filelock', '3.7.1'), ('flatbuffers', '1.12'), ('flax', '0.5.0'), ('fonttools', '4.34.4'), ('frozenlist', '1.3.1'), ('fsspec', '2022.7.1'), ('gast', '0.4.0'), ('gitdb', '4.0.9'), ('gitpython', '3.1.27'), ('glob2', '0.7'), ('google-api-core', '2.8.2'), ('google-auth', '2.10.0'), ('google-auth-oauthlib', '0.4.6'), ('google-cloud-core', '2.3.2'), ('google-cloud-storage', '2.5.0'), ('google-crc32c', '1.3.0'), ('google-pasta', '0.2.0'), ('google-resumable-media', '2.3.3'), ('googleapis-common-protos', '1.56.4'), ('grpcio', '1.47.0'), ('h5py', '3.7.0'), ('huggingface-hub', '0.8.1'), ('idna', '3.3'), ('importlib-metadata', '4.12.0'), ('importlib-resources', '5.9.0'), ('jax', '0.3.15'), ('jaxlib', '0.3.15'), ('jmespath', '1.0.1'), ('joblib', '1.1.0'), ('jsonnet', '0.18.0'), ('jsonpickle', '2.1.0'), ('keras', '2.9.0'), ('keras-preprocessing', '1.1.2'), ('kiwisolver', '1.4.4'), ('libclang', '14.0.6'), ('markdown', '3.4.1'), ('markupsafe', '2.1.1'), ('matplotlib', '3.5.2'), ('more-itertools', '8.14.0'), ('msgpack', '1.0.4'), ('multidict', '6.0.2'), ('multiprocess', '0.70.13'), ('numpy', '1.23.1'), ('oauthlib', '3.2.0'), ('opt-einsum', '3.3.0'), ('optax', '0.1.3'), ('packaging', '21.3'), ('pandas', '1.4.3'), ('pathtools', '0.1.2'), ('petname', '2.6'), ('pillow', '9.2.0'), ('pip', '22.1.2'), ('promise', '2.3'), ('protobuf', '3.19.4'), ('psutil', '5.9.1'), ('pyarrow', '9.0.0'), ('pyasn1', '0.4.8'), ('pyasn1-modules', '0.2.8'), ('pydantic', '1.9.1'), ('pydeprecate', '0.3.2'), ('pygments', '2.12.0'), ('pyparsing', '3.0.9'), ('python-dateutil', '2.8.2'), ('pytorch-lightning', '1.6.5'), ('pytz', '2022.1'), ('pyyaml', '6.0'), ('regex', '2022.7.25'), ('requests', '2.28.1'), ('requests-oauthlib', '1.3.1'), ('responses', '0.18.0'), ('rich', '12.5.1'), ('rsa', '4.9'), ('s3transfer', '0.6.0'), ('sacremoses', '0.0.53'), ('scipy', '1.9.0'), ('sentencepiece', '0.1.97'), ('sentry-sdk', '1.9.3'), ('setproctitle', '1.3.1'), ('setuptools', '61.2.0'), ('shortuuid', '1.0.9'), ('six', '1.16.0'), ('smmap', '5.0.0'), ('sqlitedict', '2.0.0'), ('tblib', '1.7.0'), ('tensorboard', '2.9.1'), ('tensorboard-data-server', '0.6.1'), ('tensorboard-plugin-wit', '1.8.1'), ('tensorflow-cpu', '2.9.1'), ('tensorflow-estimator', '2.9.0'), ('tensorflow-io-gcs-filesystem', '0.26.0'), ('termcolor', '1.1.0'), ('tokenizers', '0.12.1'), ('toolz', '0.12.0'), ('torch', '1.12.1'), ('torchmetrics', '0.9.3'), ('tqdm', '4.64.0'), ('transformers', '4.21.1'), ('typing-extensions', '4.3.0'), ('urllib3', '1.26.11'), ('wandb', '0.12.21'), ('websocket-client', '1.3.3'), ('werkzeug', '2.2.2'), ('wheel', '0.37.1'), ('wrapt', '1.14.1'), ('xxhash', '3.0.0'), ('yarl', '1.8.1'), ('zipp', '3.8.1')], git=GitMetadata(commit='0c5e94c5abe7f082be43e479b769855eecd88212', remote='git@github.com:schmmd/tango-test.git'), tango=TangoMetadata(version='0.11.0')))
```

I also noticed that if I rerun the steps with the BeakerExecutor is will run each time, but if i run it without and then with, it will simply use the cached result.

### Versions

latest

**Comment by schmmd** [comment]
I think the root cause here was that I was using a local workspace but the Beaker executor.

**Comment by schmmd** [comment]
It might be helpful to have a better exception like `"Could not find any results for step 'main'"`
