### ISSUE TITLE
importlib can't find metadata for Tango when installed outside a conda env 

### ISSUE THREAD

**Issue by isunitha98selvan** [allenai/tango#358]
### 🐛 Describe the bug

Installing Tango outside of a conda environment (for eg. on Colab) runs successfully but running tango info gives the traceback below:

Traceback (most recent call last):
  File "/usr/bin/tango", line 33, in <module>
    sys.exit(load_entry_point('ai2-tango', 'console_scripts', 'tango')())
  File "/usr/bin/tango", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/local/lib/python3.7/dist-packages/importlib_metadata/__init__.py", line 988, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/lib/python3.7/dist-packages/importlib_metadata/__init__.py", line 566, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for ai2-tango

Tango is installed in /usr/bin/ and this is not in sys.path, hence importlib is unable to find metadata for the package. 
This can also occur if pip installation inside a conda environment is the global pip and not the pip local to the conda environment. 

### Versions

Python 3.8.10

absl-py==1.2.0
-e git+https://github.com/allenai/tango.git@928aa7ae5d6b52122035c48e292326b9c923547d#egg=ai2_tango
aiohttp==3.8.1
aiosignal==1.2.0
asn1crypto==0.24.0
astunparse==1.6.3
async-timeout==4.0.2
attrs==19.3.0
Automat==0.8.0
awscli==1.18.69
backports.entry-points-selectable==1.1.1
base58==2.1.1
beaker-py==1.6.8
blessings==1.6
blinker==1.4
boto3==1.20.20
botocore==1.23.20
cached-path==1.1.5
cachetools==5.2.0
certifi==2019.11.28
chardet==3.0.4
charset-normalizer==2.1.0
chex==0.1.4
Click==7.0
click-help-colors==0.9.1
colorama==0.4.3
coloredlogs==15.0.1
command-not-found==0.3
commonmark==0.9.1
configobj==5.0.6
constantly==15.1.0
crcmod==1.7
cryptography==2.8
cycler==0.11.0
datasets==2.4.0
dbus-python==1.2.16
dill==0.3.5.1
distlib==0.3.3
distro==1.4.0
distro-info===0.23ubuntu1
dm-tree==0.1.7
docker==5.0.3
docker-pycreds==0.4.0
docutils==0.16
entrypoints==0.3
etils==0.7.1
fairscale==0.4.6
filelock==3.4.0
flatbuffers==1.12
flax==0.5.3
fonttools==4.34.4
frozenlist==1.3.0
fsspec==2022.7.1
gast==0.4.0
gitdb==4.0.9
GitPython==3.1.27
glob2==0.7
google-api-core==2.8.2
google-auth==2.9.1
google-auth-oauthlib==0.4.6
google-cloud-core==2.3.2
google-cloud-storage==2.4.0
google-crc32c==1.3.0
google-pasta==0.2.0
google-resumable-media==2.3.3
googleapis-common-protos==1.56.4
gpustat==0.6.0
greenlet==0.4.15
grpcio==1.47.0
h5py==3.7.0
httplib2==0.14.0
huggingface-hub==0.8.1
humanfriendly==10.0
hyperlink==19.0.0
idna==2.8
importlib-metadata==4.12.0
importlib-resources==5.9.0
incremental==16.10.1
iotop==0.6
jax==0.3.15
jaxlib==0.3.15
jmespath==0.9.4
joblib==1.1.0
jsonnet==0.18.0
jsonpickle==2.1.0
keras==2.9.0
Keras-Preprocessing==1.1.2
keyring==18.0.1
kiwisolver==1.4.4
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
libclang==14.0.6
Markdown==3.4.1
MarkupSafe==2.1.1
matplotlib==3.5.2
more-itertools==8.13.0
mpmath==1.2.1
msgpack==0.6.2
multidict==6.0.2
multiprocess==0.70.13
netifaces==0.10.4
numpy==1.23.1
nvidia-ml-py3==7.352.0
oauthlib==3.1.0
olefile==0.46
onnx==1.12.0
onnxconverter-common==1.12.1
onnxruntime==1.12.1
onnxruntime-tools==1.7.0
opt-einsum==3.3.0
optax==0.1.3
packaging==20.9
PAM==0.4.2
pandas==1.4.3
pathtools==0.1.2
petname==2.6
pexpect==4.6.0
Pillow==7.0.0
pkgconfig==1.5.5
platformdirs==2.4.0
promise==2.3
protobuf==4.21.4
psutil==5.8.0
py-cpuinfo==8.0.0
py3nvml==0.2.7
pyarrow==8.0.0
pyasn1==0.4.2
pyasn1-modules==0.2.1
pydantic==1.9.1
pyDeprecate==0.3.2
Pygments==2.12.0
PyGObject==3.36.0
PyHamcrest==1.9.0
PyJWT==1.7.1
pynvim==0.4.1
pyOpenSSL==19.0.0
pyparsing==3.0.6
pyserial==3.4
python-apt==2.0.0+ubuntu0.20.4.6
python-dateutil==2.8.2
python-debian===0.1.36ubuntu1
pytorch-lightning==1.6.5
pytz==2022.1
PyYAML==6.0
regex==2022.7.25
requests==2.22.0
requests-oauthlib==1.3.1
requests-unixsocket==0.2.0
responses==0.18.0
rich==12.5.1
roman==2.0.0
rsa==4.0
s3transfer==0.5.0
sacremoses==0.0.53
scipy==1.9.0
SecretStorage==2.3.1
sentencepiece==0.1.96
sentry-sdk==1.9.0
service-identity==18.1.0
setproctitle==1.3.0
shortuuid==1.0.9
simplejson==3.16.0
six==1.14.0
smmap==5.0.0
sos==4.1
sqlitedict==2.0.0
ssh-import-id==5.10
sympy==1.10.1
systemd-python==234
tblib==1.7.0
tensorboard==2.9.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow-cpu==2.9.1
tensorflow-estimator==2.9.0
tensorflow-io-gcs-filesystem==0.26.0
tensorstore==0.1.22
termcolor==1.1.0
tf2onnx==1.12.0
tokenizers==0.12.1
toolz==0.12.0
torch==1.12.0
torchmetrics==0.9.3
tqdm==4.64.0
transformers==4.21.0
Twisted==18.9.0
typing-extensions==4.3.0
ubuntu-advantage-tools==27.4
ufw==0.36
unattended-upgrades==0.1
urllib3==1.26.11
virtualenv==20.10.0
virtualfish==2.5.4
wadllib==1.3.3
wandb==0.12.21
websocket-client==1.3.3
Werkzeug==2.2.1
wrapt==1.14.1
xmltodict==0.13.0
xxhash==3.0.0
yarl==1.7.2
zipp==3.8.1
zope.interface==4.7.1

**Comment by isunitha98selvan** [comment]
Same underlying issue for #341
