### ISSUE TITLE
Beaker Workspace dies with a checksum error

### ISSUE THREAD

**Issue by dirkgr** [allenai/tango#394]
### 🐛 Describe the bug

```
2022-09-08T04:41:04.972873610Z                              Traceback (most recent call last):                                                                                                 
2022-09-08T04:41:04.972878598Z                                File "/opt/conda/bin/tango", line 8, in <module>                                                                                 
2022-09-08T04:41:04.972883935Z                                  sys.exit(main())                                                                                                               
2022-09-08T04:41:04.972888042Z                                File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__                                              
2022-09-08T04:41:04.972892983Z                                  return self.main(*args, **kwargs)                                                                                              
2022-09-08T04:41:04.972898167Z                                File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1055, in main                                                  
2022-09-08T04:41:04.972902325Z                                  rv = self.invoke(ctx)                                                                                                          
2022-09-08T04:41:04.972906495Z                                File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1657, in invoke                                                
2022-09-08T04:41:04.972910524Z                                  return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                        
2022-09-08T04:41:04.972914874Z                                File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke                                                
2022-09-08T04:41:04.972919142Z                                  return ctx.invoke(self.callback, **ctx.params)                                                                                 
2022-09-08T04:41:04.972924251Z                                File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 760, in invoke                                                 
2022-09-08T04:41:04.972940728Z                                  return __callback(*args, **kwargs)                                                                                             
2022-09-08T04:41:04.972944842Z                                File "/opt/conda/lib/python3.9/site-packages/tango/__main__.py", line 391, in beaker_executor_run                                
2022-09-08T04:41:04.972948533Z                                  executor.execute_step(step)                                                                                                    
2022-09-08T04:41:04.972952486Z                                File "/opt/conda/lib/python3.9/site-packages/tango/executor.py", line 81, in execute_step                                        
2022-09-08T04:41:04.972956126Z                                  step.ensure_result(self.workspace)                                                                                             
2022-09-08T04:41:04.972959732Z                                File "/opt/conda/lib/python3.9/site-packages/tango/step.py", line 619, in ensure_result                                          
2022-09-08T04:41:04.972963261Z                                  self.result(workspace)                                                                                                         
2022-09-08T04:41:04.972966849Z                                File "/opt/conda/lib/python3.9/site-packages/tango/step.py", line 590, in result                                                 
2022-09-08T04:41:04.972970954Z                                  return self._run_with_work_dir(workspace, needed_by=needed_by)                                                                 
2022-09-08T04:41:04.972974730Z                                File "/opt/conda/lib/python3.9/site-packages/tango/step.py", line 417, in _run_with_work_dir                                     
2022-09-08T04:41:04.972978436Z                                  kwargs = self._replace_steps_with_results(self.kwargs, workspace)                                                              
2022-09-08T04:41:04.972982198Z                                File "/opt/conda/lib/python3.9/site-packages/tango/step.py", line 565, in _replace_steps_with_results                            
2022-09-08T04:41:04.972986331Z                                  return {                                                                                                                       
2022-09-08T04:41:04.972989943Z                                File "/opt/conda/lib/python3.9/site-packages/tango/step.py", line 566, in <dictcomp>                                             
2022-09-08T04:41:04.972993661Z                                  key: self._replace_steps_with_results(value, workspace) for key, value in o.items()                                            
2022-09-08T04:41:04.972997243Z                                File "/opt/conda/lib/python3.9/site-packages/tango/step.py", line 549, in _replace_steps_with_results                            
2022-09-08T04:41:04.973000791Z                                  return o.result(workspace=workspace, needed_by=self)                                                                           
2022-09-08T04:41:04.973004589Z                                File "/opt/conda/lib/python3.9/site-packages/tango/step.py", line 598, in result                                                 
2022-09-08T04:41:04.973012015Z                                  return workspace.step_cache[self]                                                                                              
2022-09-08T04:41:04.973015897Z                                File "/opt/conda/lib/python3.9/site-packages/tango/integrations/beaker/step_cache.py", line 119, in __getitem__                  
2022-09-08T04:41:04.973019599Z                                  self.beaker.dataset.fetch(dataset, target=temp_dir, quiet=True)                                                                
2022-09-08T04:41:04.973023066Z                                File "/opt/conda/lib/python3.9/site-packages/beaker/services/dataset.py", line 260, in fetch                                     
2022-09-08T04:41:04.973026608Z                                  total_downloaded += future.result()                                                                                            
2022-09-08T04:41:04.973030056Z                                File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 439, in result                                                 
2022-09-08T04:41:04.973033618Z                                  return self.__get_result()                                                                                                     
2022-09-08T04:41:04.973037611Z                                File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result                                           
2022-09-08T04:41:04.973041371Z                                  raise self._exception                                                                                                          
2022-09-08T04:41:04.973045043Z                                File "/opt/conda/lib/python3.9/concurrent/futures/thread.py", line 58, in run                                                    
2022-09-08T04:41:04.973048717Z                                  result = self.fn(*self.args, **self.kwargs)                                                                                    
2022-09-08T04:41:04.973052403Z                                File "/opt/conda/lib/python3.9/site-packages/beaker/services/dataset.py", line 727, in _download_file                            
2022-09-08T04:41:04.973055958Z                                  for chunk in self._stream_file(storage, file_info, validate_checksum=validate_checksum):                                       
2022-09-08T04:41:04.973059402Z                                File "/opt/conda/lib/python3.9/site-packages/beaker/services/dataset.py", line 706, in _stream_file                              
2022-09-08T04:41:04.973062996Z                                  raise ChecksumFailedError(                                                                                                     
2022-09-08T04:41:04.973066656Z                              beaker.exceptions.ChecksumFailedError: Checksum for 'result/data.pt' failed. Expected                                              
2022-09-08T04:41:04.973070278Z                              'wdca6Cq/NqkK0TnRV6F8vJkyjdeG5C8+6qdoUN3pUwc=', got 'SHA256 cTF7tpSn7nb2nD4SDdaFPvRsMCZ48xJTF9hZovuKlJQ='.   
```

Is this recoverable?

### Versions

pdf

**Comment by epwalsh** [comment]
I think https://github.com/allenai/beaker-py/pull/152 will make downloads more robust, so the probability of this happening should be ~nil. We should reopen this if we still see these errors after the https://github.com/allenai/beaker-py/pull/152 merges.
