### ISSUE TITLE
Another place where we need to be more robust to beaker timeouts

### ISSUE THREAD

**Issue by dirkgr** [allenai/tango#396]
### 🐛 Describe the bug

https://beaker.org/ex/01GCDCM42CFMK9YENG3Y21VZER/tasks/01GCDCM43MY13H6PAPA82F8RPT/job/01GCDCMAJB0A7SMH69DMWW03YZ

```
2022-09-08T09:07:22.783694830Z                              Traceback (most recent call last):                                                                                                 
2022-09-08T09:07:22.783701183Z                                File "/opt/conda/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request                              
2022-09-08T09:07:22.783706363Z                                  six.raise_from(e, None)                                                                                                        
2022-09-08T09:07:22.783710932Z                                File "<string>", line 3, in raise_from                                                                                           
2022-09-08T09:07:22.783715832Z                                File "/opt/conda/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request                              
2022-09-08T09:07:22.783720492Z                                  httplib_response = conn.getresponse()                                                                                          
2022-09-08T09:07:22.783724830Z                                File "/opt/conda/lib/python3.9/http/client.py", line 1377, in getresponse                                                        
2022-09-08T09:07:22.783729700Z                                  response.begin()                                                                                                               
2022-09-08T09:07:22.783733758Z                                File "/opt/conda/lib/python3.9/http/client.py", line 320, in begin                                                               
2022-09-08T09:07:22.783738347Z                                  version, status, reason = self._read_status()                                                                                  
2022-09-08T09:07:22.783742345Z                                File "/opt/conda/lib/python3.9/http/client.py", line 281, in _read_status                                                        
2022-09-08T09:07:22.783748017Z                                  line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")                                                                       
2022-09-08T09:07:22.783773608Z                                File "/opt/conda/lib/python3.9/socket.py", line 704, in readinto                                                                 
2022-09-08T09:07:22.783777716Z                                  return self._sock.recv_into(b)                                                                                                 
2022-09-08T09:07:22.783781273Z                                File "/opt/conda/lib/python3.9/ssl.py", line 1241, in recv_into                                                                  
2022-09-08T09:07:22.783785141Z                                  return self.read(nbytes, buffer)                                                                                               
2022-09-08T09:07:22.783788668Z                                File "/opt/conda/lib/python3.9/ssl.py", line 1099, in read                                                                       
2022-09-08T09:07:22.783792556Z                                  return self._sslobj.read(len, buffer)                                                                                          
2022-09-08T09:07:22.783796193Z                              socket.timeout: The read operation timed out                                                                                       
2022-09-08T09:07:22.783799910Z                                                                                                                                                                 
2022-09-08T09:07:22.783803477Z                              During handling of the above exception, another exception occurred:                                                                
2022-09-08T09:07:22.783807405Z                                                                                                                                                                 
2022-09-08T09:07:22.783811033Z                              Traceback (most recent call last):                                                                                                 
2022-09-08T09:07:22.783814830Z                                File "/opt/conda/lib/python3.9/site-packages/requests/adapters.py", line 440, in send                                            
2022-09-08T09:07:22.783818848Z                                  resp = conn.urlopen(                                                                                                           
2022-09-08T09:07:22.783822666Z                                File "/opt/conda/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen                                    
2022-09-08T09:07:22.783826293Z                                  retries = retries.increment(                                                                                                   
2022-09-08T09:07:22.783830020Z                                File "/opt/conda/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment                                      
2022-09-08T09:07:22.783833618Z                                  raise six.reraise(type(error), error, _stacktrace)                                                                             
2022-09-08T09:07:22.783837445Z                                File "/opt/conda/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise                                      
2022-09-08T09:07:22.783845201Z                                  raise value                                                                                                                    
2022-09-08T09:07:22.783849089Z                                File "/opt/conda/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen                                    
2022-09-08T09:07:22.783852736Z                                  httplib_response = self._make_request(                                                                                         
2022-09-08T09:07:22.783856503Z                                File "/opt/conda/lib/python3.9/site-packages/urllib3/connectionpool.py", line 451, in _make_request                              
2022-09-08T09:07:22.783860111Z                                  self._raise_timeout(err=e, url=url, timeout_value=read_timeout)                                                                
2022-09-08T09:07:22.783863968Z                                File "/opt/conda/lib/python3.9/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout                             
2022-09-08T09:07:22.783867606Z                                  raise ReadTimeoutError(                                                                                                        
2022-09-08T09:07:22.783872105Z                              urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='data.beaker.org', port=443): Read timed out. (read                  
2022-09-08T09:07:22.783875732Z                              timeout=5.0)                                                                                                                       
2022-09-08T09:07:22.783879279Z                                                                                                                                                                 
2022-09-08T09:07:22.783882826Z                              During handling of the above exception, another exception occurred:                                                                
2022-09-08T09:07:22.783886423Z                                                                                                                                                                 
2022-09-08T09:07:22.783889930Z                              Traceback (most recent call last):                                                                                                 
2022-09-08T09:07:22.783893447Z                                File "/opt/conda/bin/tango", line 8, in <module>                                                                                 
2022-09-08T09:07:22.783897335Z                                  sys.exit(main())                                                                                                               
2022-09-08T09:07:22.783901143Z                                File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__                                              
2022-09-08T09:07:22.783904750Z                                  return self.main(*args, **kwargs)                                                                                              
2022-09-08T09:07:22.783911533Z                                File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1055, in main                                                  
2022-09-08T09:07:22.783915521Z                                  rv = self.invoke(ctx)                                                                                                          
2022-09-08T09:07:22.783919449Z                                File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1657, in invoke                                                
2022-09-08T09:07:22.783923147Z                                  return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                        
2022-09-08T09:07:22.783926674Z                                File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke                                                
2022-09-08T09:07:22.783930341Z                                  return ctx.invoke(self.callback, **ctx.params)                                                                                 
2022-09-08T09:07:22.783934179Z                                File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 760, in invoke                                                 
2022-09-08T09:07:22.783937826Z                                  return __callback(*args, **kwargs)                                                                                             
2022-09-08T09:07:22.783941423Z                                File "/opt/conda/lib/python3.9/site-packages/tango/__main__.py", line 391, in beaker_executor_run                                
2022-09-08T09:07:22.783945331Z                                  executor.execute_step(step)                                                                                                    
2022-09-08T09:07:22.783948898Z                                File "/opt/conda/lib/python3.9/site-packages/tango/executor.py", line 81, in execute_step                                        
2022-09-08T09:07:22.783952475Z                                  step.ensure_result(self.workspace)                                                                                             
2022-09-08T09:07:22.783956243Z                                File "/opt/conda/lib/python3.9/site-packages/tango/step.py", line 619, in ensure_result                                          
2022-09-08T09:07:22.783959820Z                                  self.result(workspace)                                                                                                         
2022-09-08T09:07:22.783963437Z                                File "/opt/conda/lib/python3.9/site-packages/tango/step.py", line 590, in result                                                 
2022-09-08T09:07:22.783967285Z                                  return self._run_with_work_dir(workspace, needed_by=needed_by)                                                                 
2022-09-08T09:07:22.783970812Z                                File "/opt/conda/lib/python3.9/site-packages/tango/step.py", line 428, in _run_with_work_dir                                     
2022-09-08T09:07:22.783974439Z                                  result = workspace.step_finished(self, result)                                                                                 
2022-09-08T09:07:22.783981173Z                                File "/opt/conda/lib/python3.9/site-packages/tango/integrations/beaker/workspace.py", line 163, in step_finished                 
2022-09-08T09:07:22.783984900Z                                  self.cache[step] = result                                                                                                      
2022-09-08T09:07:22.783988487Z                                File "/opt/conda/lib/python3.9/site-packages/tango/integrations/beaker/step_cache.py", line 144, in __setitem__                  
2022-09-08T09:07:22.783992185Z                                  self._sync_step_dataset(step, temp_dir)                                                                                        
2022-09-08T09:07:22.783995742Z                                File "/opt/conda/lib/python3.9/site-packages/tango/integrations/beaker/step_cache.py", line 72, in                               
2022-09-08T09:07:22.783999399Z                              _sync_step_dataset                                                                                                                 
2022-09-08T09:07:22.784002946Z                                  self.beaker.dataset.sync(dataset, objects_dir, quiet=True)                                                                     
2022-09-08T09:07:22.784006513Z                                File "/opt/conda/lib/python3.9/site-packages/beaker/services/dataset.py", line 472, in sync                                      
2022-09-08T09:07:22.784010211Z                                  actual_size = future.result()                                                                                                  
2022-09-08T09:07:22.784013768Z                                File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 439, in result                                                 
2022-09-08T09:07:22.784018016Z                                  return self.__get_result()                                                                                                     
2022-09-08T09:07:22.784021603Z                                File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result                                           
2022-09-08T09:07:22.784025221Z                                  raise self._exception                                                                                                          
2022-09-08T09:07:22.784028808Z                                File "/opt/conda/lib/python3.9/concurrent/futures/thread.py", line 58, in run                                                    
2022-09-08T09:07:22.784032746Z                                  result = self.fn(*self.args, **self.kwargs)                                                                                    
2022-09-08T09:07:22.784036253Z                                File "/opt/conda/lib/python3.9/site-packages/beaker/services/dataset.py", line 595, in _upload_file                              
2022-09-08T09:07:22.784039900Z                                  response = self.request(                                                                                                       
2022-09-08T09:07:22.784044249Z                                File "/opt/conda/lib/python3.9/site-packages/beaker/services/service_client.py", line 98, in request                             
2022-09-08T09:07:22.784050932Z                                  return make_request(self.beaker._session)                                                                                      
2022-09-08T09:07:22.784054710Z                                File "/opt/conda/lib/python3.9/site-packages/beaker/services/service_client.py", line 73, in make_request                        
2022-09-08T09:07:22.784058647Z                                  response = getattr(session, method.lower())(                                                                                   
2022-09-08T09:07:22.784062395Z                                File "/opt/conda/lib/python3.9/site-packages/requests/sessions.py", line 601, in patch                                           
2022-09-08T09:07:22.784066273Z                                  return self.request('PATCH', url, data=data, **kwargs)                                                                         
2022-09-08T09:07:22.784070461Z                                File "/opt/conda/lib/python3.9/site-packages/requests/sessions.py", line 529, in request                                         
2022-09-08T09:07:22.784073908Z                                  resp = self.send(prep, **send_kwargs)                                                                                          
2022-09-08T09:07:22.784076954Z                                File "/opt/conda/lib/python3.9/site-packages/requests/sessions.py", line 645, in send                                            
2022-09-08T09:07:22.784080070Z                                  r = adapter.send(request, **kwargs)                                                                                            
2022-09-08T09:07:22.784083126Z                                File "/opt/conda/lib/python3.9/site-packages/requests/adapters.py", line 532, in send                                            
2022-09-08T09:07:22.784086203Z                                  raise ReadTimeout(e, request=request)                                                                                          
2022-09-08T09:07:22.784089229Z                              requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='data.beaker.org', port=443): Read timed out. (read                      
2022-09-08T09:07:22.784092515Z                              timeout=5.0)                                                                                                                       
```

### Versions

asd

**Comment by dirkgr** [comment]
Also https://beaker.org/ex/01GCD7GF1HWSQQAM4FEXKQW1V7/tasks/01GCD7GF3D6ZATTN3S45NM9GSR/job/01GCD7GSGHTBZ7SEYAECF4T2G5
